// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZG1pRtAdcyybMvY0JhAi5w-b5wu-NMw0',
    appId: '1:935014426563:web:b0c63899f965ec8560ff76',
    messagingSenderId: '935014426563',
    projectId: 'mynotes-flutter-firebase-app',
    authDomain: 'mynotes-flutter-firebase-app.firebaseapp.com',
    storageBucket: 'mynotes-flutter-firebase-app.appspot.com',
    measurementId: 'G-XRJPQPGWBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBViB5TpcRr4wmanNSyAwfjI4WO84E_3jA',
    appId: '1:935014426563:android:10a465afea9401a560ff76',
    messagingSenderId: '935014426563',
    projectId: 'mynotes-flutter-firebase-app',
    storageBucket: 'mynotes-flutter-firebase-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChZn4hXrZPxE7rnbwB_ku9ObdoTib5ZcY',
    appId: '1:935014426563:ios:bbca84411c91874c60ff76',
    messagingSenderId: '935014426563',
    projectId: 'mynotes-flutter-firebase-app',
    storageBucket: 'mynotes-flutter-firebase-app.appspot.com',
    iosClientId: '935014426563-p0k8414tphvbp53m81iis33erurpqnic.apps.googleusercontent.com',
    iosBundleId: 'me.tusharchavan.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChZn4hXrZPxE7rnbwB_ku9ObdoTib5ZcY',
    appId: '1:935014426563:ios:bbca84411c91874c60ff76',
    messagingSenderId: '935014426563',
    projectId: 'mynotes-flutter-firebase-app',
    storageBucket: 'mynotes-flutter-firebase-app.appspot.com',
    iosClientId: '935014426563-p0k8414tphvbp53m81iis33erurpqnic.apps.googleusercontent.com',
    iosBundleId: 'me.tusharchavan.mynotes',
  );
}
